// Code generated by "enumer -type=DDLExecutionMode -trimprefix=DDLExecutionMode -transform=snake_upper"; DO NOT EDIT.

package enums

import (
	"fmt"
	"strings"
)

const _DDLExecutionModeName = "SYNCASYNCASYNC_WAIT"

var _DDLExecutionModeIndex = [...]uint8{0, 4, 9, 19}

const _DDLExecutionModeLowerName = "syncasyncasync_wait"

func (i DDLExecutionMode) String() string {
	if i < 0 || i >= DDLExecutionMode(len(_DDLExecutionModeIndex)-1) {
		return fmt.Sprintf("DDLExecutionMode(%d)", i)
	}
	return _DDLExecutionModeName[_DDLExecutionModeIndex[i]:_DDLExecutionModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DDLExecutionModeNoOp() {
	var x [1]struct{}
	_ = x[DDLExecutionModeSync-(0)]
	_ = x[DDLExecutionModeAsync-(1)]
	_ = x[DDLExecutionModeAsyncWait-(2)]
}

var _DDLExecutionModeValues = []DDLExecutionMode{DDLExecutionModeSync, DDLExecutionModeAsync, DDLExecutionModeAsyncWait}

var _DDLExecutionModeNameToValueMap = map[string]DDLExecutionMode{
	_DDLExecutionModeName[0:4]:       DDLExecutionModeSync,
	_DDLExecutionModeLowerName[0:4]:  DDLExecutionModeSync,
	_DDLExecutionModeName[4:9]:       DDLExecutionModeAsync,
	_DDLExecutionModeLowerName[4:9]:  DDLExecutionModeAsync,
	_DDLExecutionModeName[9:19]:      DDLExecutionModeAsyncWait,
	_DDLExecutionModeLowerName[9:19]: DDLExecutionModeAsyncWait,
}

var _DDLExecutionModeNames = []string{
	_DDLExecutionModeName[0:4],
	_DDLExecutionModeName[4:9],
	_DDLExecutionModeName[9:19],
}

// DDLExecutionModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DDLExecutionModeString(s string) (DDLExecutionMode, error) {
	if val, ok := _DDLExecutionModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DDLExecutionModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DDLExecutionMode values", s)
}

// DDLExecutionModeValues returns all values of the enum
func DDLExecutionModeValues() []DDLExecutionMode {
	return _DDLExecutionModeValues
}

// DDLExecutionModeStrings returns a slice of all String values of the enum
func DDLExecutionModeStrings() []string {
	strs := make([]string, len(_DDLExecutionModeNames))
	copy(strs, _DDLExecutionModeNames)
	return strs
}

// IsADDLExecutionMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DDLExecutionMode) IsADDLExecutionMode() bool {
	for _, v := range _DDLExecutionModeValues {
		if i == v {
			return true
		}
	}
	return false
}
