// Code generated by "enumer -type=DdlInTransactionMode -trimprefix=DdlInTransactionMode -transform=snake_upper"; DO NOT EDIT.

package enums

import (
	"fmt"
	"strings"
)

const _DdlInTransactionModeName = "FAILALLOW_IN_EMPTY_TRANSACTIONAUTO_COMMIT_TRANSACTION"

var _DdlInTransactionModeIndex = [...]uint8{0, 4, 30, 53}

const _DdlInTransactionModeLowerName = "failallow_in_empty_transactionauto_commit_transaction"

func (i DdlInTransactionMode) String() string {
	if i < 0 || i >= DdlInTransactionMode(len(_DdlInTransactionModeIndex)-1) {
		return fmt.Sprintf("DdlInTransactionMode(%d)", i)
	}
	return _DdlInTransactionModeName[_DdlInTransactionModeIndex[i]:_DdlInTransactionModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DdlInTransactionModeNoOp() {
	var x [1]struct{}
	_ = x[DdlInTransactionModeFail-(0)]
	_ = x[DdlInTransactionModeAllowInEmptyTransaction-(1)]
	_ = x[DdlInTransactionModeAutoCommitTransaction-(2)]
}

var _DdlInTransactionModeValues = []DdlInTransactionMode{DdlInTransactionModeFail, DdlInTransactionModeAllowInEmptyTransaction, DdlInTransactionModeAutoCommitTransaction}

var _DdlInTransactionModeNameToValueMap = map[string]DdlInTransactionMode{
	_DdlInTransactionModeName[0:4]:        DdlInTransactionModeFail,
	_DdlInTransactionModeLowerName[0:4]:   DdlInTransactionModeFail,
	_DdlInTransactionModeName[4:30]:       DdlInTransactionModeAllowInEmptyTransaction,
	_DdlInTransactionModeLowerName[4:30]:  DdlInTransactionModeAllowInEmptyTransaction,
	_DdlInTransactionModeName[30:53]:      DdlInTransactionModeAutoCommitTransaction,
	_DdlInTransactionModeLowerName[30:53]: DdlInTransactionModeAutoCommitTransaction,
}

var _DdlInTransactionModeNames = []string{
	_DdlInTransactionModeName[0:4],
	_DdlInTransactionModeName[4:30],
	_DdlInTransactionModeName[30:53],
}

// DdlInTransactionModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DdlInTransactionModeString(s string) (DdlInTransactionMode, error) {
	if val, ok := _DdlInTransactionModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DdlInTransactionModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DdlInTransactionMode values", s)
}

// DdlInTransactionModeValues returns all values of the enum
func DdlInTransactionModeValues() []DdlInTransactionMode {
	return _DdlInTransactionModeValues
}

// DdlInTransactionModeStrings returns a slice of all String values of the enum
func DdlInTransactionModeStrings() []string {
	strs := make([]string, len(_DdlInTransactionModeNames))
	copy(strs, _DdlInTransactionModeNames)
	return strs
}

// IsADdlInTransactionMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DdlInTransactionMode) IsADdlInTransactionMode() bool {
	for _, v := range _DdlInTransactionModeValues {
		if i == v {
			return true
		}
	}
	return false
}
