// Code generated by "enumer -type=DumpCyclicMode -trimprefix=DumpCyclicMode -transform=snake_upper"; DO NOT EDIT.

package enums

import (
	"fmt"
	"strings"
)

const _DumpCyclicModeName = "REJECTMUTATE"

var _DumpCyclicModeIndex = [...]uint8{0, 6, 12}

const _DumpCyclicModeLowerName = "rejectmutate"

func (i DumpCyclicMode) String() string {
	if i < 0 || i >= DumpCyclicMode(len(_DumpCyclicModeIndex)-1) {
		return fmt.Sprintf("DumpCyclicMode(%d)", i)
	}
	return _DumpCyclicModeName[_DumpCyclicModeIndex[i]:_DumpCyclicModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DumpCyclicModeNoOp() {
	var x [1]struct{}
	_ = x[DumpCyclicModeReject-(0)]
	_ = x[DumpCyclicModeMutate-(1)]
}

var _DumpCyclicModeValues = []DumpCyclicMode{DumpCyclicModeReject, DumpCyclicModeMutate}

var _DumpCyclicModeNameToValueMap = map[string]DumpCyclicMode{
	_DumpCyclicModeName[0:6]:       DumpCyclicModeReject,
	_DumpCyclicModeLowerName[0:6]:  DumpCyclicModeReject,
	_DumpCyclicModeName[6:12]:      DumpCyclicModeMutate,
	_DumpCyclicModeLowerName[6:12]: DumpCyclicModeMutate,
}

var _DumpCyclicModeNames = []string{
	_DumpCyclicModeName[0:6],
	_DumpCyclicModeName[6:12],
}

// DumpCyclicModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DumpCyclicModeString(s string) (DumpCyclicMode, error) {
	if val, ok := _DumpCyclicModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DumpCyclicModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DumpCyclicMode values", s)
}

// DumpCyclicModeValues returns all values of the enum
func DumpCyclicModeValues() []DumpCyclicMode {
	return _DumpCyclicModeValues
}

// DumpCyclicModeStrings returns a slice of all String values of the enum
func DumpCyclicModeStrings() []string {
	strs := make([]string, len(_DumpCyclicModeNames))
	copy(strs, _DumpCyclicModeNames)
	return strs
}

// IsADumpCyclicMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DumpCyclicMode) IsADumpCyclicMode() bool {
	for _, v := range _DumpCyclicModeValues {
		if i == v {
			return true
		}
	}
	return false
}
