// Code generated by "enumer -type=SavepointSupport -trimprefix=SavepointSupport -transform=snake_upper"; DO NOT EDIT.

package enums

import (
	"fmt"
	"strings"
)

const _SavepointSupportName = "DISABLEDENABLED"

var _SavepointSupportIndex = [...]uint8{0, 8, 15}

const _SavepointSupportLowerName = "disabledenabled"

func (i SavepointSupport) String() string {
	if i < 0 || i >= SavepointSupport(len(_SavepointSupportIndex)-1) {
		return fmt.Sprintf("SavepointSupport(%d)", i)
	}
	return _SavepointSupportName[_SavepointSupportIndex[i]:_SavepointSupportIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SavepointSupportNoOp() {
	var x [1]struct{}
	_ = x[SavepointSupportDisabled-(0)]
	_ = x[SavepointSupportEnabled-(1)]
}

var _SavepointSupportValues = []SavepointSupport{SavepointSupportDisabled, SavepointSupportEnabled}

var _SavepointSupportNameToValueMap = map[string]SavepointSupport{
	_SavepointSupportName[0:8]:       SavepointSupportDisabled,
	_SavepointSupportLowerName[0:8]:  SavepointSupportDisabled,
	_SavepointSupportName[8:15]:      SavepointSupportEnabled,
	_SavepointSupportLowerName[8:15]: SavepointSupportEnabled,
}

var _SavepointSupportNames = []string{
	_SavepointSupportName[0:8],
	_SavepointSupportName[8:15],
}

// SavepointSupportString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SavepointSupportString(s string) (SavepointSupport, error) {
	if val, ok := _SavepointSupportNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SavepointSupportNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SavepointSupport values", s)
}

// SavepointSupportValues returns all values of the enum
func SavepointSupportValues() []SavepointSupport {
	return _SavepointSupportValues
}

// SavepointSupportStrings returns a slice of all String values of the enum
func SavepointSupportStrings() []string {
	strs := make([]string, len(_SavepointSupportNames))
	copy(strs, _SavepointSupportNames)
	return strs
}

// IsASavepointSupport returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SavepointSupport) IsASavepointSupport() bool {
	for _, v := range _SavepointSupportValues {
		if i == v {
			return true
		}
	}
	return false
}
