// Code generated by "enumer -type=StringQuoteMode -trimprefix=StringQuoteMode -transform=snake_upper"; DO NOT EDIT.

package enums

import (
	"fmt"
	"strings"
)

const _StringQuoteModeName = "NONEAUTOALWAYS"

var _StringQuoteModeIndex = [...]uint8{0, 4, 8, 14}

const _StringQuoteModeLowerName = "noneautoalways"

func (i StringQuoteMode) String() string {
	if i < 0 || i >= StringQuoteMode(len(_StringQuoteModeIndex)-1) {
		return fmt.Sprintf("StringQuoteMode(%d)", i)
	}
	return _StringQuoteModeName[_StringQuoteModeIndex[i]:_StringQuoteModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StringQuoteModeNoOp() {
	var x [1]struct{}
	_ = x[StringQuoteModeNone-(0)]
	_ = x[StringQuoteModeAuto-(1)]
	_ = x[StringQuoteModeAlways-(2)]
}

var _StringQuoteModeValues = []StringQuoteMode{StringQuoteModeNone, StringQuoteModeAuto, StringQuoteModeAlways}

var _StringQuoteModeNameToValueMap = map[string]StringQuoteMode{
	_StringQuoteModeName[0:4]:       StringQuoteModeNone,
	_StringQuoteModeLowerName[0:4]:  StringQuoteModeNone,
	_StringQuoteModeName[4:8]:       StringQuoteModeAuto,
	_StringQuoteModeLowerName[4:8]:  StringQuoteModeAuto,
	_StringQuoteModeName[8:14]:      StringQuoteModeAlways,
	_StringQuoteModeLowerName[8:14]: StringQuoteModeAlways,
}

var _StringQuoteModeNames = []string{
	_StringQuoteModeName[0:4],
	_StringQuoteModeName[4:8],
	_StringQuoteModeName[8:14],
}

// StringQuoteModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StringQuoteModeString(s string) (StringQuoteMode, error) {
	if val, ok := _StringQuoteModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StringQuoteModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StringQuoteMode values", s)
}

// StringQuoteModeValues returns all values of the enum
func StringQuoteModeValues() []StringQuoteMode {
	return _StringQuoteModeValues
}

// StringQuoteModeStrings returns a slice of all String values of the enum
func StringQuoteModeStrings() []string {
	strs := make([]string, len(_StringQuoteModeNames))
	copy(strs, _StringQuoteModeNames)
	return strs
}

// IsAStringQuoteMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StringQuoteMode) IsAStringQuoteMode() bool {
	for _, v := range _StringQuoteModeValues {
		if i == v {
			return true
		}
	}
	return false
}
