// Code generated by "enumer -type=StyledMode -trimprefix=StyledMode -transform=snake_upper"; DO NOT EDIT.

package enums

import (
	"fmt"
	"strings"
)

const _StyledModeName = "AUTOTRUEFALSE"

var _StyledModeIndex = [...]uint8{0, 4, 8, 13}

const _StyledModeLowerName = "autotruefalse"

func (i StyledMode) String() string {
	if i < 0 || i >= StyledMode(len(_StyledModeIndex)-1) {
		return fmt.Sprintf("StyledMode(%d)", i)
	}
	return _StyledModeName[_StyledModeIndex[i]:_StyledModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StyledModeNoOp() {
	var x [1]struct{}
	_ = x[StyledModeAuto-(0)]
	_ = x[StyledModeTrue-(1)]
	_ = x[StyledModeFalse-(2)]
}

var _StyledModeValues = []StyledMode{StyledModeAuto, StyledModeTrue, StyledModeFalse}

var _StyledModeNameToValueMap = map[string]StyledMode{
	_StyledModeName[0:4]:       StyledModeAuto,
	_StyledModeLowerName[0:4]:  StyledModeAuto,
	_StyledModeName[4:8]:       StyledModeTrue,
	_StyledModeLowerName[4:8]:  StyledModeTrue,
	_StyledModeName[8:13]:      StyledModeFalse,
	_StyledModeLowerName[8:13]: StyledModeFalse,
}

var _StyledModeNames = []string{
	_StyledModeName[0:4],
	_StyledModeName[4:8],
	_StyledModeName[8:13],
}

// StyledModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StyledModeString(s string) (StyledMode, error) {
	if val, ok := _StyledModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StyledModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to StyledMode values", s)
}

// StyledModeValues returns all values of the enum
func StyledModeValues() []StyledMode {
	return _StyledModeValues
}

// StyledModeStrings returns a slice of all String values of the enum
func StyledModeStrings() []string {
	strs := make([]string, len(_StyledModeNames))
	copy(strs, _StyledModeNames)
	return strs
}

// IsAStyledMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i StyledMode) IsAStyledMode() bool {
	for _, v := range _StyledModeValues {
		if i == v {
			return true
		}
	}
	return false
}
