// Code generated by "enumer -type=WidthStrategy -trimprefix=WidthStrategy -transform=snake_upper"; DO NOT EDIT.

package enums

import (
	"fmt"
	"strings"
)

const _WidthStrategyName = "GREEDY_FREQUENCYPROPORTIONALMARGINAL_COST"

var _WidthStrategyIndex = [...]uint8{0, 16, 28, 41}

const _WidthStrategyLowerName = "greedy_frequencyproportionalmarginal_cost"

func (i WidthStrategy) String() string {
	if i < 0 || i >= WidthStrategy(len(_WidthStrategyIndex)-1) {
		return fmt.Sprintf("WidthStrategy(%d)", i)
	}
	return _WidthStrategyName[_WidthStrategyIndex[i]:_WidthStrategyIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _WidthStrategyNoOp() {
	var x [1]struct{}
	_ = x[WidthStrategyGreedyFrequency-(0)]
	_ = x[WidthStrategyProportional-(1)]
	_ = x[WidthStrategyMarginalCost-(2)]
}

var _WidthStrategyValues = []WidthStrategy{WidthStrategyGreedyFrequency, WidthStrategyProportional, WidthStrategyMarginalCost}

var _WidthStrategyNameToValueMap = map[string]WidthStrategy{
	_WidthStrategyName[0:16]:       WidthStrategyGreedyFrequency,
	_WidthStrategyLowerName[0:16]:  WidthStrategyGreedyFrequency,
	_WidthStrategyName[16:28]:      WidthStrategyProportional,
	_WidthStrategyLowerName[16:28]: WidthStrategyProportional,
	_WidthStrategyName[28:41]:      WidthStrategyMarginalCost,
	_WidthStrategyLowerName[28:41]: WidthStrategyMarginalCost,
}

var _WidthStrategyNames = []string{
	_WidthStrategyName[0:16],
	_WidthStrategyName[16:28],
	_WidthStrategyName[28:41],
}

// WidthStrategyString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func WidthStrategyString(s string) (WidthStrategy, error) {
	if val, ok := _WidthStrategyNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _WidthStrategyNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to WidthStrategy values", s)
}

// WidthStrategyValues returns all values of the enum
func WidthStrategyValues() []WidthStrategy {
	return _WidthStrategyValues
}

// WidthStrategyStrings returns a slice of all String values of the enum
func WidthStrategyStrings() []string {
	strs := make([]string, len(_WidthStrategyNames))
	copy(strs, _WidthStrategyNames)
	return strs
}

// IsAWidthStrategy returns "true" if the value is listed in the enum definition. "false" otherwise
func (i WidthStrategy) IsAWidthStrategy() bool {
	for _, v := range _WidthStrategyValues {
		if i == v {
			return true
		}
	}
	return false
}
