changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Bug Fixes
      labels:
        - bug
    - title: New Features
      labels:
        - enhancement
    - title: Misc
      labels:
        - "*"
