// Code generated by "stringer -type=DisplayMode"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DisplayModeTable-0]
	_ = x[DisplayModeTableComment-1]
	_ = x[DisplayModeTableDetailComment-2]
	_ = x[DisplayModeVertical-3]
	_ = x[DisplayModeTab-4]
	_ = x[DisplayModeHTML-5]
	_ = x[DisplayModeXML-6]
	_ = x[DisplayModeCSV-7]
}

const _DisplayMode_name = "DisplayModeTableDisplayModeTableCommentDisplayModeTableDetailCommentDisplayModeVerticalDisplayModeTabDisplayModeHTMLDisplayModeXMLDisplayModeCSV"

var _DisplayMode_index = [...]uint8{0, 16, 39, 68, 87, 101, 116, 130, 144}

func (i DisplayMode) String() string {
	if i < 0 || i >= DisplayMode(len(_DisplayMode_index)-1) {
		return "DisplayMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DisplayMode_name[_DisplayMode_index[i]:_DisplayMode_index[i+1]]
}
